version: "3.5"
services:
  arangodb:
    image: arangodb:latest
    restart: always
    ports:
      - 50001:8529
    environment:
      ARANGO_ROOT_PASSWORD: letmein
    volumes:
      - C:/work/arangodbstorage:/var/lib/arangodb3
    networks:
      # Networks to join (Services on the same network can communicate with each other using their name)
      - stg
    #command: arangod --server.authentication=false

  backend:
    # Configuration for building the docker image for the service
    build:
      context: ./back # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "50002:50002" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    environment:
      ENVTORUN: dev
    

    depends_on:
      - arangodb
    networks:
      # Networks to join (Services on the same network can communicate with each other using their name)
      - stg
    #healthcheck:
    #   test: ["CMD", "curl", "-f", "http://arangodb:8529"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5


  frontend:
    # Configuration for building the docker image for the service
    build:
      context: ./front # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "50003:80" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    environment:
      ENVTORUN: dev
      API_HOST: http://localhost:50002/api/v1

    networks:
      # Networks to join (Services on the same network can communicate with each other using their name)
      - stg

networks:
  stg:
